version: "3.7"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: ./api
        environment:
            AES_KEY: ${AES_KEY}
            IV_KEY: ${IV_KEY}
        ports:
            - "4000:4000"
    client:
        build:
            dockerfile: Dockerfile
            context: ./client
        environment:
            BASE_URL: ${BASE_URL}
        ports:
            - "5000:8080"
