version: "3.7"
services:
    api:
        image: tolumide/maily_be
        environment:
            AES_KEY: ${AES_KEY}
            IV_KEY: ${IV_KEY}
        ports:
            - "9000:4000"
    client:
        image: tolumide/maily_fe
        environment:
            BASE_URL: ${BASE_URL}
        ports:
            - "5000:8080"
