export const FETCH_ALL_MAILS_PENDING = "FETCH_ALL_MAILS_PENDING";
export const FETCH_ALL_MAILS_FAILURE = "FETCH_ALL_MAILS_FAILURE";
export const FETCH_ALL_MAILS_SUCCESS = "FETCH_ALL_MAILS_SUCCESS";

export default [
    FETCH_ALL_MAILS_FAILURE,
    FETCH_ALL_MAILS_PENDING,
    FETCH_ALL_MAILS_SUCCESS,
];
