export const FETCH_SPECIFIC_MAIL_PENDING = "FETCH_SPECIFIC_MAIL_PENDING";
export const FETCH_SPECIFIC_MAIL_FAILURE = "FETCH_SPECIFIC_MAIL_FAILURE";
export const FETCH_SPECIFIC_MAIL_SUCCESS = "FETCH_SPECIFIC_MAIL_SUCCESS";

export default [
    FETCH_SPECIFIC_MAIL_PENDING,
    FETCH_SPECIFIC_MAIL_FAILURE,
    FETCH_SPECIFIC_MAIL_SUCCESS,
];
